services:
  tts:
    image: bendangelo/kokoro-tts:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4321:4321
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [ gpu ]
    environment:
      LOG_LEVEL: INFO
      KOKORO_API_KEY: hello
